### ISSUE TITLE
0.1.10 checklist

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#118]
Expected release date: Week of November 2nd

- [x] Fix https://github.com/crytic/crytic-compile/issues/113
- [x] Fix https://github.com/crytic/crytic-compile/issues/112
- [x] Fix https://github.com/crytic/crytic-compile/issues/123
- [x] Write changelog

**Comment by montyly** [comment]
I have added #123 to the list, as we have multiple users asking for it
