### ISSUE TITLE
Add support for Brownie

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#2]
https://github.com/HyperLink-Technology/brownie

**Comment by montyly** [comment]
## Task Description
The goal is to add the Brownie support to crytic-compile

- [ ] Create a new platform to support Brownie 
- [ ] Follow the [adding a new platform documentation](https://github.com/crytic/crytic-compile/wiki/Adding-a-new-platform)

## Acceptance criteria
- [ ] The project can be compiled runing `crytic-compile .`
- [ ] `slither .` run slither on the project.
- [ ] A unit test is prepared to be added to travis. The unit test follows the format of the [existing ones](https://github.com/crytic/crytic-compile/issues/3)

## Required Skills
- [ ] Experience with Python 3.6
- [ ] Experience with Solidity smart contracts

## Prefered Skills
- [ ] Experience with libraries design


Our documentation to add new platform is fairly young, but we have several existing platforms. This issue requires to be able to produce good code without significant documentation.

Feel free to ask questions here, or join our [slack](https://empireslacking.herokuapp.com/) (#ethereum)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 DAI (200.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/2/3220).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/crytic-compile/2/3220).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $136,771.03 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [abhimanyu121](https://gitcoin.co/profile/abhimanyu121) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/2/3220?mutate_worker_action=approve&worker=abhimanyu121) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/2/3220?mutate_worker_action=reject&worker=abhimanyu121))_.**

In the first step, I would get used to the codebase of Slither to work in a better manner, afterward, I would find and implement the most efficient way print name and details of the constructor that is being called.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/2/3220).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [gungz](https://gitcoin.co/profile/gungz) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/2/3220?mutate_worker_action=approve&worker=gungz) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/2/3220?mutate_worker_action=reject&worker=gungz))_.**

To be honest, first of all what I need to know is what kind of support will need to be added to Brownie because the description of this bounty is not clear on what will need to be done for this bounty to be deemed as finished.
From then only I can make a plan on what I can do to solve this bounty.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/2/3220).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [gungz](https://gitcoin.co/profile/gungz) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/2/3220?mutate_worker_action=approve&worker=gungz) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/2/3220?mutate_worker_action=reject&worker=gungz))_.**

To be honest, first of all what I need to know is what kind of support will need to be added to Brownie because the description of this bounty is not clear on what will need to be done for this bounty to be deemed as finished.
From then only I can make a plan on what I can do to solve this bounty.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/2/3220).

**Comment by montyly** [comment]
Hi @gungz, 

Thank you for your interest in this work. My understanding is that nothing needs to be added to brownie, as their output format seems to contain all the information: https://eth-brownie.readthedocs.io/en/latest/compile.html#build-json-format. Though I haven't used heavily brownie.

This issue mostly requires to convert their JSON structure to crytic-compile internal format

**Comment by iamdefinitelyahuman** [comment]
I've tried to mimic Truffle's build format as closely as possible for exactly this situation.

That said - if there are any modifications required on Brownie's end or if anything is unclear, I'm happy to assist.

**Comment by Gungz** [comment]
Thanks, indeed from reading the code of cryptic-compile and Brownie, I think I understand what needs to be done, basically you want to enable support for doing compilation using Brownie from cryptic-compile, am I right ? The only thing is now I will not be able to directly work on it, as I have some other crucial things for next 2-3 weeks, I'll re-apply in next 2-3 weeks if there're still nobody working on it.

Sorry for my late reply, I just checked this GitHub again after some time and I didn't get any notification in my email when @montyly  reply in the comment.

**Comment by montyly** [comment]
Thank you @iamdefinitelyahuman for your support!

@Gungz, you are right. crytic-compile is a kind of proxy we are using to connect all our ethereum tools (slither, manticore, echidna, ..) to any smart contract compilation platform. Let us know when you are available again.

**Comment by pbteja1998** [comment]
@montyly is this still available, can I work on this?

**Comment by montyly** [comment]
@pbteja1998 yes, I don't think @Gungz started the work.

**Comment by pbteja1998** [comment]
@montyly From what I understand, you can compile contracts using `brownie`. But they require specific json format to be able to compile. But `cryptic-compile` uses different json format, I have to make changes in code such that I will be able to convert the current json format to brownie json format so that I will be able to compile contracts using brownie. There are other platforms that are integrated already, I can go through them to get much better idea.

**Comment by pbteja1998** [comment]
@montyly can I give this a try? If so, please approve me on gitcoin.

**Comment by pbteja1998** [comment]
Just realized that I understood it wrongly. Compiling a contract with brownie will generate a json file in their format (https://eth-brownie.readthedocs.io/en/latest/compile.html#build-json-format). I have to take this json file and convert it into format of crytic_compile.

@montyly Is this correct?

**Comment by Gungz** [comment]
Hi @montyly and @pbteja1998, sorry for my late reply, yes, I have not started and probably won't be able to for now. I'll withdraw from the application.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 10 months, 1 week from now.
Please review their action plans below:


**1) [excerebrose](https://gitcoin.co/profile/excerebrose) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/2/3220?mutate_worker_action=approve&worker=excerebrose) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/2/3220?mutate_worker_action=reject&worker=excerebrose))_.**

Happy to take over this, having looked into brownie before, could get this up and running in the next 3 days or so.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/2/3220).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 200.0 DAI  (200.0 USD @ $1.0/DAI) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $128,552.96 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by sssubik** [comment]
Is brownie supported through slither now??
```
KeyError: 'absolutePath'
ERROR:root:None
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.7.0-py3.6.egg/slither/__main__.py", line 712, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.7.0-py3.6.egg/slither/__main__.py", line 71, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/ssubik/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 1076, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/ssubik/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 137, in __init__
    self._compile(**kwargs)
  File "/home/ssubik/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 987, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/ssubik/.local/lib/python3.6/site-packages/crytic_compile/platform/brownie.py", line 77, in compile
    _iterate_over_files(crytic_compile, self._target, filenames)
  File "/home/ssubik/.local/lib/python3.6/site-packages/crytic_compile/platform/brownie.py", line 141, in _iterate_over_files
    filename_txt = target_loaded["ast"]["absolutePath"]
KeyError: 'absolutePath'

```
Getting these errors.
