### ISSUE TITLE
New release checklist

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#220]
- [ ] https://github.com/crytic/crytic-compile/issues/210
- [ ] https://github.com/crytic/crytic-compile/issues/208
- [ ] https://github.com/crytic/crytic-compile/issues/218
- [ ] https://github.com/crytic/crytic-compile/issues/219
- [ ] https://github.com/crytic/crytic-compile/issues/209
- [ ] https://github.com/crytic/crytic-compile/issues/197
- [ ] https://github.com/crytic/crytic-compile/issues/157 (@NatalieChin80 )
