### ISSUE TITLE
Add support for Waffle

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#3]
https://ethereum-waffle.readthedocs.io/en/latest/index.html

**Comment by montyly** [comment]
## Task Description
The goal is to add the Waffle support to crytic-compile

- [ ] Create a new platform to support waffle 
- [ ] Follow the [adding a new platform documentation](https://github.com/crytic/crytic-compile/wiki/Adding-a-new-platform)

## Acceptance criteria
- [ ] The project can be compiled runing `crytic-compile .`
- [ ] `slither .` run slither on the project.
- [ ] A unit test is prepared to be added to travis. The unit test follows the format of the [existing ones](https://github.com/crytic/crytic-compile/issues/3)

## Required Skills
- [ ] Experience with Python 3.6
- [ ] Experience with Solidity smart contracts

## Prefered Skills
- [ ] Experience with libraries design


Our documentation to add new platform is fairly young, but we have several existing platforms. This issue requires to be able to produce good code without significant documentation.

Feel free to ask questions here, or join our [slack](https://empireslacking.herokuapp.com/) (#ethereum)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 DAI (200.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/3/3219).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/crytic-compile/3/3219).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $136,574.09 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [skyge](https://gitcoin.co/profile/skyge) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?mutate_worker_action=approve&worker=skyge) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?mutate_worker_action=reject&worker=skyge))_.**

I have experience with Python and Solidity.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/3/3219).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 11 months, 2 weeks from now.
Please review their action plans below:


**1) [skyge](https://gitcoin.co/profile/skyge) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?mutate_worker_action=approve&worker=skyge) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?mutate_worker_action=reject&worker=skyge))_.**

I have experience with Python and Solidity.
**2) [gasiortomasz](https://gitcoin.co/profile/gasiortomasz) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?mutate_worker_action=approve&worker=gasiortomasz) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?mutate_worker_action=reject&worker=gasiortomasz))_.**

Hi, I have experience using Waffle. Also, I am pretty fluent in python. This ticket shouldn't take long.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/3/3219).

**Comment by gitcoinbot** [comment]
@gasiortomasz Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=100)

**Comment by gasiortomasz** [comment]
Hi I plan to work on this issue on Sunday/Monday. 4-5th of August

**Comment by ceresstation** [comment]
Hi @gasiortomasz can you guarantee that? I'd just hate to hold off on reassigning for a week only to have the issue left undone. Totally willing to trust you on it if you can provide that guarantee.

**Comment by gasiortomasz** [comment]
Hi @ceresstation. Sorry for late response. Unfortunately I will have to postpone my work on that. I'll re-apply when I'll find extra time.

**Comment by ceresstation** [comment]
Hey @skyge would love to have you take this one on if you have time.

**Comment by gitcoinbot** [comment]
@skyge Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=100)

**Comment by Skyge** [comment]
Hi, this is similar to `add support for Brownie`, I will finish it in four weeks.

**Comment by gitcoinbot** [comment]
@skyge Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=100)

**Comment by Skyge** [comment]
@montyly when I try to add a new platform, I have got to have the following functions:`def compile(crytic_compile, target, **kwargs)`, so how can I set these parameters: 
- crytic_compile.abis
- crytic_compile.bytecodes_init
- crytic_compile.bytecodes_runtime
is there an existing approach to compile the contract to get these? or I should get these through my own way?

**Comment by gitcoinbot** [comment]
@skyge Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 9 months from now.
Please review their action plans below:


**1) [nicstr](https://gitcoin.co/profile/nicstr) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?mutate_worker_action=approve&worker=nicstr) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/3/3219?mutate_worker_action=reject&worker=nicstr))_.**

A pull request is already ready to be merged.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/3/3219).

**Comment by montyly** [comment]
Hi @NicsTr, thank you for your contribution, #44 is merged.

@ceresstation: can you validate the bounty to @NicsTr? Thanks!

**Comment by montyly** [comment]
@ceresstation: can you pay the bounty to @NicsTr ? Thank you

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 200.00000  DAI (200.0 USD @ $1.0/DAI) has been granted to @nicstr for this issue from @ceresstation. ⚡️ 

Nice work @nicstr! Your tip has automatically been deposited in the ETH address we have on file.

 * $86538.45 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__This Bounty has been completed.__

Additional Tips for this Bounty:
* ceresstation tipped 200.0000 DAI worth 200.0 USD to nicstr.

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/3/3219)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $97,065.08 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
