### ISSUE TITLE
Add --ignore-compile flag

### ISSUE THREAD

**Issue by montyly** [crytic/crytic-compile#49]
If the flag is set to True, it will active `--PLATFORM-ignore-compile` for all the platform implementing the feature

**Comment by Patil2099** [comment]
@montyly Where do I have to set the flag?
Thanks!

**Comment by montyly** [comment]
## Task Description
Add a generic --ignore-compile flag, that will be equivalent to all `--PLATFORM-ignore-compile` to true.

## Acceptance criteria
- [ ] The flag is added in [cryticparser/cryticparser.py#L4-L27](https://github.com/crytic/crytic-compile/blob/master/crytic_compile/cryticparser/cryticparser.py#L4-L27)
- [ ] The flag has a [default value](https://github.com/crytic/crytic-compile/blob/master/crytic_compile/cryticparser/defaults.py) set to False
- [ ] Once set to True, all the platform with the `--PLATFORM-ignore-compile` ignore the compilation. For example, Truffle flag is set here: https://github.com/crytic/crytic-compile/blob/eac05ea263adc31545ea07d30b761bd5b3a25541/crytic_compile/platform/truffle.py#L22

## Required Skills
- [ ]  Experience with Python 3.6
- [ ]  Experience with Solidity smart contracts

Feel free to ask questions here, or join our [slack](https://empireslacking.herokuapp.com/) (#ethereum)

**Comment by montyly** [comment]
Hi @Patil2099, thank you for your interest in this issue. I hope that the description above answers your question. 
We are creating a gitcoin bounty for this issue.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 50.0 SAI (50.0 USD @ $1.0/SAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/49/3729).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/crytic-compile/49/3729).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $114,857.00 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by karansinghgit** [comment]
@montyly Since no one seems to be working on this, could you assign this to me? Also, could you explain 
`Once set to True, all the platform with the --PLATFORM-ignore-compile ignore the compilation.`

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 1 month from now.
Please review their action plans below:


**1) [karansinghgit](https://gitcoin.co/karansinghgit) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?mutate_worker_action=approve&worker=karansinghgit) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?mutate_worker_action=reject&worker=karansinghgit))_.**

I'd like to take a shot at this. I think it will just require modifications in a couple of files.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/49/3729).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 1 month from now.
Please review their action plans below:


**1) [karansinghgit](https://gitcoin.co/karansinghgit) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?mutate_worker_action=approve&worker=karansinghgit) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?mutate_worker_action=reject&worker=karansinghgit))_.**

I'd like to take a shot at this. I think it will just require modifications in a couple of files.
**2) [fritzjay](https://gitcoin.co/fritzjay) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?mutate_worker_action=approve&worker=fritzjay) | [reject worker](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?mutate_worker_action=reject&worker=fritzjay))_.**

Hey there! I've been working with python for a couple years now and would love to help update your app. As per your request, I would add the --ignore-compile flag to cryticparser.py and update each platform specific compile function.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/49/3729).

**Comment by karansinghgit** [comment]
@montyly Could you please assign this to me?

**Comment by gitcoinbot** [comment]
@karansinghgit Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=100)

**Comment by karansinghgit** [comment]
@gitcoinbot Already sent a PR

**Comment by gitcoinbot** [comment]
@karansinghgit Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/crytic-compile/49/3729?snooze=100)

**Comment by montyly** [comment]
@ceresstation: the work was completed by @karansinghgit (https://github.com/crytic/crytic-compile/issues/49). Can you send the bounty? thanks

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 50.0 SAI (50.0 USD @ $1.0/SAI) has been submitted by__:

 1. [@karansinghgit](https://gitcoin.co/karansinghgit)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/crytic/crytic-compile/pull/55) by @karansinghgit

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/49/3729)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/crytic-compile/49/3729).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $100,594.23 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 50.0 SAI (50.0 USD @ $1.0/SAI)  attached to this issue has been approved & issued to @karansinghgit.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/crytic-compile/49/3729)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $96,971.06 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
